package dev.tggamesyt.szar;

import net.minecraft.block.BlockState;
import net.minecraft.block.Blocks;
import net.minecraft.block.entity.BlockEntity;
import net.minecraft.nbt.NbtCompound;
import net.minecraft.nbt.NbtList;
import net.minecraft.nbt.NbtOps;
import net.minecraft.nbt.NbtString;
import net.minecraft.util.math.BlockPos;
import net.minecraft.world.World;
import org.jetbrains.annotations.Nullable;
import net.minecraft.network.listener.ClientPlayPacketListener;
import net.minecraft.network.packet.Packet;
import net.minecraft.network.packet.s2c.play.BlockEntityUpdateS2CPacket;
import java.util.*;

public class TrackerBlockEntity extends BlockEntity {
    // Add these fields
    public BlockState originalPortalBlock = Blocks.AIR.getDefaultState();
    public boolean placedByPlayer = true; // false = auto-generated by the system
    // The overworld entry coords (used by nether-side tracker to know where to send players back)
    public double returnX, returnY, returnZ;
    // Whether this tracker is in the nether or overworld
    // BlockPos of the paired tracker in the other dimension
    public BlockPos pairedTrackerPos = null;

    // UUIDs of players currently inside the dimension via this portal
    private final Set<UUID> playersInside = new HashSet<>();

    public TrackerBlockEntity(BlockPos pos, BlockState state) {
        super(Szar.TRACKER_BLOCK_ENTITY, pos, state);
    }

    public void addPlayer(UUID uuid) {
        playersInside.add(uuid);
        markDirty();
    }

    public void removePlayer(UUID uuid) {
        playersInside.remove(uuid);
        markDirty();
    }

    public boolean hasPlayers() {
        return !playersInside.isEmpty();
    }

    public Set<UUID> getPlayersInside() {
        return playersInside;
    }

    @Override
    public void writeNbt(NbtCompound nbt) {
        super.writeNbt(nbt);
        nbt.putDouble("ReturnX", returnX);
        nbt.putDouble("ReturnY", returnY);
        nbt.putDouble("ReturnZ", returnZ);

        if (pairedTrackerPos != null) {
            nbt.putInt("PairedX", pairedTrackerPos.getX());
            nbt.putInt("PairedY", pairedTrackerPos.getY());
            nbt.putInt("PairedZ", pairedTrackerPos.getZ());
        }

        NbtList list = new NbtList();
        for (UUID uuid : playersInside) {
            list.add(NbtString.of(uuid.toString()));
        }
        nbt.put("PlayersInside", list);
        NbtCompound originalBlock = new NbtCompound();
        BlockState.CODEC.encodeStart(NbtOps.INSTANCE, originalPortalBlock)
                .result()
                .ifPresent(nbt1 -> originalBlock.put("State", nbt1));
        nbt.put("OriginalPortalBlock", originalBlock);
        nbt.putBoolean("PlacedByPlayer", placedByPlayer);
        if (parentTrackerPos != null) {
            nbt.putInt("ParentX", parentTrackerPos.getX());
            nbt.putInt("ParentY", parentTrackerPos.getY());
            nbt.putInt("ParentZ", parentTrackerPos.getZ());
        }

        NbtList portalList = new NbtList();
        for (BlockPos p : controlledPortals) {
            NbtCompound entry = new NbtCompound();
            entry.putInt("X", p.getX());
            entry.putInt("Y", p.getY());
            entry.putInt("Z", p.getZ());
            portalList.add(entry);
        }
        nbt.put("ControlledPortals", portalList);
    }

    @Override
    public void readNbt(NbtCompound nbt) {
        super.readNbt(nbt);
        returnX = nbt.getDouble("ReturnX");
        returnY = nbt.getDouble("ReturnY");
        returnZ = nbt.getDouble("ReturnZ");

        if (nbt.contains("PairedX")) {
            pairedTrackerPos = new BlockPos(
                    nbt.getInt("PairedX"),
                    nbt.getInt("PairedY"),
                    nbt.getInt("PairedZ")
            );
        }

        NbtList list = nbt.getList("PlayersInside", 8);
        playersInside.clear();
        for (int i = 0; i < list.size(); i++) {
            playersInside.add(UUID.fromString(list.getString(i)));
        }
        if (nbt.contains("OriginalPortalBlock")) {
            NbtCompound originalBlock = nbt.getCompound("OriginalPortalBlock");
            if (originalBlock.contains("State")) {
                BlockState.CODEC.parse(NbtOps.INSTANCE, originalBlock.get("State"))
                        .result()
                        .ifPresent(s -> originalPortalBlock = s);
            }
        }
        placedByPlayer = nbt.getBoolean("PlacedByPlayer");
        if (nbt.contains("ParentX")) {
            parentTrackerPos = new BlockPos(
                    nbt.getInt("ParentX"),
                    nbt.getInt("ParentY"),
                    nbt.getInt("ParentZ")
            );
        } else {
            parentTrackerPos = null;
        }

        controlledPortals.clear();
        NbtList portalList = nbt.getList("ControlledPortals", 10);
        for (int i = 0; i < portalList.size(); i++) {
            NbtCompound entry = portalList.getCompound(i);
            controlledPortals.add(new BlockPos(
                    entry.getInt("X"), entry.getInt("Y"), entry.getInt("Z")
            ));
        }
    }

    // null = this is a root/parent tracker
// non-null = this is a child, delegate to parent
    @Nullable
    public BlockPos parentTrackerPos = null;

    // List of portal positions this tracker controls (only used by parent)
    private final List<BlockPos> controlledPortals = new ArrayList<>();

    public void addPortal(BlockPos portalPos) {
        if (!controlledPortals.contains(portalPos)) {
            controlledPortals.add(portalPos);
            markDirty();
        }
    }

    public void removePortal(BlockPos portalPos) {
        controlledPortals.remove(portalPos);
        markDirty();
    }

    public List<BlockPos> getControlledPortals() {
        return controlledPortals;
    }

    public boolean isChild() {
        return parentTrackerPos != null;
    }

    // Resolves to the root parent, following chain if needed
    public TrackerBlockEntity getRoot(World world) {
        if (parentTrackerPos == null) return this;
        if (world.getBlockEntity(parentTrackerPos) instanceof TrackerBlockEntity parent) {
            return parent.getRoot(world);
        }
        // Parent is gone — become root
        parentTrackerPos = null;
        markDirty();
        return this;
    }
    @Override
    public Packet<ClientPlayPacketListener> toUpdatePacket() {
        return BlockEntityUpdateS2CPacket.create(this);
    }

    @Override
    public NbtCompound toInitialChunkDataNbt() {
        return createNbt();
    }
}
